server:
  port: 7001
eureka:
  instance:
    hostname: www.eureka-7001.com
  client:
    fetch-registry: false #是否注册到eureka
    register-with-eureka: false
    service-url:
      defaultZone:  http://www.eureka-7001.com:7001/eureka/